%YAML:1.0
################################################################################
## NOISE parameters:

NOISE:
  # IMU parameters:
  w_var: 1e-4
  dbg_var: 3.6733e-5
  a_var: 1e-2
  dba_var: 7e-2
  # INIT parameters:
  q_var_init: 1e-5
  bg_var_init: 1e-2
  v_var_init: 1e-2
  ba_var_init: 1e-2
  p_var_init: 1e-12

################################################################################
## TRACKER parameters:
TRACKER:
  feature_cov: 2
  n_grid_rows: 10
  n_grid_cols: 10

################################################################################
## MSCKF parameters:
MSCKF:
  max_gn_cost_norm: 7
  translation_threshold: 0.1
  min_rcond: 3e-12
  keyframe_transl_dist: 0.5
  keyframe_rot_dist: 0.5
  min_track_length: 5
  max_track_length: 50
  max_cam_states: 30
  ransac_threshold: 0.00000002


################################################################################
## CAMERA parameters:
# intrinsics
Camera:
  cameraDistortionModel: radtan
  target: circlegrid
  width: 640
  height: 480
  camera_id: 0
  CM: !!opencv-matrix
    rows: 4
    cols: 1
    dt: d
    data: [530.8659660649512, 529.3305111783843, 313.32531436313576, 238.55408596195164]
  DM: !!opencv-matrix
    rows: 5
    cols: 1
    dt: d
    data: [0.04104734576136917, -0.07618037333503923, 0.0012671421066435828, 0.00047760663793306493, 0 ]
# extrinsic
Camera-IMU:
  R_ci: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 0.00591558, -0.99996419, 0.00605248, -0.99976871, -0.00578906, 0.02071268, -0.0206769, -0.00617361, -0.99976715 ]
  p_ci: !!opencv-matrix
    rows: 3
    cols: 1
    dt: d
    data: [0.0895778, 0.01455079, -0.00696331]

## done
