%YAML:1.0
################################################################################
## NOISE parameters:

NOISE:
  # IMU parameters:
  w_var: 1e-5
  dbg_var: 4e-5
  a_var: 1e-3
  dba_var: 7e-2
  # INIT parameters:
  q_var_init: 1e-2
  bg_var_init: 1e-5
  v_var_init: 1e-2
  ba_var_init: 1e-4
  p_var_init: 1e-2

################################################################################
## TRACKER parameters:
TRACKER:
  feature_cov: 7
  n_grid_rows: 8
  n_grid_cols: 8
  
################################################################################
## INIT parameters:
INIT:
  stand_still_time:2
################################################################################
## MSCKF parameters:
MSCKF:
  max_gn_cost_norm: 7
  translation_threshold: 0.1
  min_rcond: 3e-12
  keyframe_transl_dist: 0.005
  keyframe_rot_dist: 0.05
  min_track_length: 3
  max_track_length: 50
  max_cam_states: 20
  ransac_threshold: 0.000002


################################################################################
## CAMERA parameters: from euroc dataset
# intrinsics
Camera:
  cameraDistortionModel: radtan
  CM: !!opencv-matrix
    rows: 4
    cols: 1
    dt: d
    data: [458.654, 457.296, 367.215, 248.375]
  DM: !!opencv-matrix
    rows: 4
    cols: 1
    dt: d
    data: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05 ]
# extrinsic: R is row-wise R(1,1), R(1,2), R(1,3), R(2,1), R(2,2) ...
Camera-IMU:
  R_ci: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 0.0148655429818, -0.999880929698, 0.00414029679422, 0.999557249008, 0.0149672133247, 0.025715529948, -0.0257744366974, 0.00375618835797, 0.999660727178 ]
  p_ci: !!opencv-matrix
    rows: 3
    cols: 1
    dt: d
    data: [-0.0216401454975, -0.064676986768, 0.00981073058949]

## done
